# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MPC.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MPC.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tMPC.proto\"\x15\n\x06Status\x12\x0b\n\x03res\x18\x01 \x01(\x05\"(\n\tServerDef\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\")\n\nServerSpec\x12\x1b\n\x07servers\x18\x01 \x03(\x0b\x32\n.ServerDef\".\n\nTensorSpec\x12\x11\n\ttensor_id\x18\x01 \x01(\x05\x12\r\n\x05shape\x18\x02 \x03(\x05\"\x1f\n\x06Tensor\x12\x15\n\rtensor_buffer\x18\x01 \x01(\x0c\"\"\n\x0b\x43omputation\x12\x13\n\x0b\x63omputation\x18\x01 \x01(\t2\xa9\x01\n\tMPCServer\x12\'\n\rSetServerSpec\x12\x0b.ServerSpec\x1a\x07.Status\"\x00\x12#\n\tGetTensor\x12\x0b.TensorSpec\x1a\x07.Tensor\"\x00\x12&\n\x0c\x44\x65leteTensor\x12\x0b.TensorSpec\x1a\x07.Status\"\x00\x12&\n\x07\x43ompute\x12\x0c.Computation\x1a\x0b.TensorSpec\"\x00\x62\x06proto3')
)




_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='Status.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=34,
)


_SERVERDEF = _descriptor.Descriptor(
  name='ServerDef',
  full_name='ServerDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ServerDef.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='ServerDef.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=76,
)


_SERVERSPEC = _descriptor.Descriptor(
  name='ServerSpec',
  full_name='ServerSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='servers', full_name='ServerSpec.servers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=119,
)


_TENSORSPEC = _descriptor.Descriptor(
  name='TensorSpec',
  full_name='TensorSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor_id', full_name='TensorSpec.tensor_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='TensorSpec.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=167,
)


_TENSOR = _descriptor.Descriptor(
  name='Tensor',
  full_name='Tensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor_buffer', full_name='Tensor.tensor_buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=200,
)


_COMPUTATION = _descriptor.Descriptor(
  name='Computation',
  full_name='Computation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='computation', full_name='Computation.computation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=236,
)

_SERVERSPEC.fields_by_name['servers'].message_type = _SERVERDEF
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['ServerDef'] = _SERVERDEF
DESCRIPTOR.message_types_by_name['ServerSpec'] = _SERVERSPEC
DESCRIPTOR.message_types_by_name['TensorSpec'] = _TENSORSPEC
DESCRIPTOR.message_types_by_name['Tensor'] = _TENSOR
DESCRIPTOR.message_types_by_name['Computation'] = _COMPUTATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'MPC_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  ))
_sym_db.RegisterMessage(Status)

ServerDef = _reflection.GeneratedProtocolMessageType('ServerDef', (_message.Message,), dict(
  DESCRIPTOR = _SERVERDEF,
  __module__ = 'MPC_pb2'
  # @@protoc_insertion_point(class_scope:ServerDef)
  ))
_sym_db.RegisterMessage(ServerDef)

ServerSpec = _reflection.GeneratedProtocolMessageType('ServerSpec', (_message.Message,), dict(
  DESCRIPTOR = _SERVERSPEC,
  __module__ = 'MPC_pb2'
  # @@protoc_insertion_point(class_scope:ServerSpec)
  ))
_sym_db.RegisterMessage(ServerSpec)

TensorSpec = _reflection.GeneratedProtocolMessageType('TensorSpec', (_message.Message,), dict(
  DESCRIPTOR = _TENSORSPEC,
  __module__ = 'MPC_pb2'
  # @@protoc_insertion_point(class_scope:TensorSpec)
  ))
_sym_db.RegisterMessage(TensorSpec)

Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), dict(
  DESCRIPTOR = _TENSOR,
  __module__ = 'MPC_pb2'
  # @@protoc_insertion_point(class_scope:Tensor)
  ))
_sym_db.RegisterMessage(Tensor)

Computation = _reflection.GeneratedProtocolMessageType('Computation', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTATION,
  __module__ = 'MPC_pb2'
  # @@protoc_insertion_point(class_scope:Computation)
  ))
_sym_db.RegisterMessage(Computation)



_MPCSERVER = _descriptor.ServiceDescriptor(
  name='MPCServer',
  full_name='MPCServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=239,
  serialized_end=408,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetServerSpec',
    full_name='MPCServer.SetServerSpec',
    index=0,
    containing_service=None,
    input_type=_SERVERSPEC,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTensor',
    full_name='MPCServer.GetTensor',
    index=1,
    containing_service=None,
    input_type=_TENSORSPEC,
    output_type=_TENSOR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTensor',
    full_name='MPCServer.DeleteTensor',
    index=2,
    containing_service=None,
    input_type=_TENSORSPEC,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Compute',
    full_name='MPCServer.Compute',
    index=3,
    containing_service=None,
    input_type=_COMPUTATION,
    output_type=_TENSORSPEC,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MPCSERVER)

DESCRIPTOR.services_by_name['MPCServer'] = _MPCSERVER

# @@protoc_insertion_point(module_scope)
